openrewrite/rewrite-maven-plugin

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java, src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
Created new goal that lists all available recipes and their visitors on project build.
=> New Rewrite Discover Goal

pom.xml
https://maven.apache.org/surefire/maven-surefire-plugin/
=> upgrade to maven-surefire-plugin 3.0.0-M5

pom.xml, src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java, src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java, src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java, src/main/java/org/openrewrite/maven/RewriteFixMojo.java
Also ensure that recipes like ChangePackage can move files
=> Update for rewrite 7.0.0-rc.5

pom.xml, src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
=> adds recipe descriptor to discover task output

pom.xml
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
=> stop using bintray.com

src/test/java/org/openrewrite/maven/PomCacheIT.java, src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java, src/test/java/org/openrewrite/maven/RewriteDryRunIT.java, src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/a/pom.xml, src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/a/src/main/java/sample/MyInterface.java, src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/a/src/main/java/sample/SimplifyBooleanSample.java, src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/b/pom.xml, src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/b/src/main/java/sample/EmptyBlockSample.java, src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/pom.xml, src/test/resources-its/org/openrewrite/maven/PomCacheIT/single_project/pom.xml, src/test/resources-its/org/openrewrite/maven/RewriteCycloneDxIT/multi_module_project/pom.xml, src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_reads_rewrite_yml/pom.xml, src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_reads_rewrite_yml/rewrite.yml, src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/pom.xml, src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/rewrite.yml, src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/rewrite.yml, src/test/resources-its/org/openrewrite/maven/RewriteRunIT/single_project/pom.xml
see: https://github.com/openrewrite/rewrite-maven-plugin/issues/118
=> Tests from pom.xmls resolve respective rewrite yml configuration files

README.md, pom.xml
bootstrap the plugin with the plugin
=> rewrite plugin applied to itself

src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java, src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
fixes https://github.com/openrewrite/rewrite-maven-plugin/issues/144
prevents this peculiar output where it was going `[INFO] [info] ...` on lines
=> do not directly instantiate log from getLog as a class field, call method each time

pom.xml
Reverts openrewrite/rewrite-maven-plugin#130
=> Revert "chore(ci): bump maven-release-plugin from 3.0.0-M1 to 3.0.0-M4"

pom.xml, src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java, src/main/java/org/openrewrite/maven/ui/RecipeDescriptorTree.java, src/main/java/org/openrewrite/maven/ui/RecipeDescriptorTreePrompter.java, src/main/java/org/openrewrite/maven/ui/package-info.java
see https://github.com/openrewrite/rewrite-maven-plugin/issues/138
```sh
./mvnw rewrite:discover -Dinteractive
```
=> RewriteDiscover categorized recipes available on classpath

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
part of https://github.com/openrewrite/rewrite-maven-plugin/issues/159 and the work in https://github.com/openrewrite/rewrite-maven-plugin/commit/666d44bc072dc49280e736430c2c0e9ec6965b01 and linked to the gradle-plugin equivalent https://github.com/openrewrite/rewrite-gradle-plugin/pull/47
Allows passing configuration of 
```
<configuration>
<failOnInvalidActiveRecipes>{true,false}</failOnInvalidActiveRecipes>
</configuration>
```
to control whether validation on an activeRecipe or it's respective sub recipes warrants throwing a program-terminating exception. The default is passive, `false`, which is permissive.
=> failOnInvalidActiveRecipes to configure handling activeRecipe validation errors throwing exceptions

src/main/java/org/openrewrite/maven/RemoveMojo.java, src/test/java/org/openrewrite/maven/RemoveMojoIT.java, src/test/resources-its/org/openrewrite/maven/RemoveMojoIT/single_project/pom.xml
=> Fix and test RemoveMojo

pom.xml, src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
closes https://github.com/openrewrite/rewrite-maven-plugin/issues/257
Polish, move to provided scope
Move from apache commons to upstream openrewrite
Explicitly declaring dependencies otherwise brought in transitively
Consolidate property of maven-plugin-tools for applicable dependencies and plugins
Factor out junit deps
=> Dependencies and tidyup

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java, src/main/java/org/openrewrite/maven/ArtifactResolver.java, src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java, src/main/java/org/openrewrite/maven/ConfigureMojo.java, src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java, src/main/java/org/openrewrite/maven/InitMojo.java, src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java, src/main/java/org/openrewrite/maven/MavenOptsHelper.java, src/main/java/org/openrewrite/maven/ResourceParser.java, src/main/java/org/openrewrite/maven/RewriteDryRunMojo.java
(Just a lil' syntactic tidy-up before making actual semantic changes)
=> Polish, rewrite autoformat

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java, src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java, src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java, src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java, src/test/java/org/openrewrite/maven/MavenMojoProjectParserIT.java, src/test/resources-its/org/openrewrite/maven/MavenMojoProjectParserIT/maven_mojo_project_parser_resolves_settings/pom.xml, src/test/resources-its/org/openrewrite/maven/MavenMojoProjectParserIT/maven_mojo_project_parser_resolves_settings/settings.xml
See: https://github.com/openrewrite/rewrite-maven-plugin/issues/152
=> Let Maven resolve settings.xml content for us, get values from MavenExecutionRequest

.gitignore, src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java, src/test/java/org/openrewrite/maven/RewriteDryRunIT.java, src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/pom.xml, src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/rewrite.yml, src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/src/main/java/sample/EmptyBlockSample.java, src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/src/main/java/sample/SimplifyBooleanSample.java
Right now, the active recipes end up in an unordered Set and they are
being applied in a random order.
=> Respect active recipes order

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java, src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java, src/main/java/org/openrewrite/maven/ConfigureMojo.java, src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java, src/main/java/org/openrewrite/maven/InitMojo.java, src/main/java/org/openrewrite/maven/RemoveMojo.java
Changes:
- Updated `write` to use `SourceFile#getCharset()`
=> Use character encoding on the AST to write.

pom.xml, src/main/java/org/openrewrite/maven/ResourceParser.java
Changes:
- Resources in the current maven project that are not considered exclusions will be added quarks.
fixes #346
=> Added support for `Quark`s.

pom.xml
It eases testing snapshot version of rewrite and rewrite-plugin
=> Switch to rewrite 7.24.0-SNAPSHOT

src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Changes:
- Added `MavenMojoProjectParser$resetTypeCache` to optionally reset the type cache between parsing modules while running the plugin per module.
fixes #373
=> Added a `MavenMojoProjectParser$resetTypeCache`.

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java, src/test/java/org/openrewrite/maven/RewriteDryRunIT.java, src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/no_plugin_in_pom/pom.xml, src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/no_plugin_in_pom/src/test/java/sample/SampleTest.java
=> Bugfix: transitive dependencies of recipeArtifactCoordinates jars will now be available during recipe execution

src/main/java/org/openrewrite/maven/TimeUtils.java, src/test/java/org/openrewrite/maven/AbstractRewriteMojoTest.java, src/test/java/org/openrewrite/maven/BasicIT.java, src/test/java/org/openrewrite/maven/ConfigureMojoIT.java, src/test/java/org/openrewrite/maven/DiscoverNoActiveRecipeIT.java, src/test/java/org/openrewrite/maven/InitMojoIT.java, src/test/java/org/openrewrite/maven/RemoveMojoIT.java, src/test/java/org/openrewrite/maven/RewriteCycloneDxIT.java, src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java, src/test/java/org/openrewrite/maven/RewriteDryRunIT.java, src/test/java/org/openrewrite/maven/RewriteRunIT.java
* remove also unused class TimeUtils.
=> fix Remove public modifier from integration tests classes (#496)

pom.xml
=> fix - Remove unused dependency maven-compat (#499)

src/test/java/org/openrewrite/maven/BasicIT.java
=> Ignore known Mac OS warning

src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java, src/test/java/org/openrewrite/maven/RewriteRunIT.java, src/test/resources-its/org/openrewrite/maven/RewriteRunIT/cloud_suitability_project/pom.xml
Fixes https://github.com/openrewrite/rewrite-cloud-suitability-analyzer/issues/6
=> Do not write to quark

src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Related to https://github.com/openrewrite/rewrite/pull/3105 and https://github.com/openrewrite/rewrite-kotlin/pull/95.
=> Correctly and completely manage source set assignment to all compilation units

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
`AbstractRewriteMojo.java`  code clean
=> refactor: code clean

pom.xml
To suppress dependency vulnerability report https://github.com/moderneinc/dependency-vulnerability-reports/issues/511
=> bump `jackson` version to suppress dependency vulnerability report

pom.xml
This should slightly reduce the risk of version conflicts.
=> Add `rewrite-bom` BOM dependency

src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java, src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java, src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
Delaying execution to the end of multi-module project
Fix #719
=> Delaying execution to the end of multi-module project

.mvn/wrapper/maven-wrapper.properties
=> Upgrade to Maven Wrapper 3.9.6

src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java, src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
=> Standardize on `-Drewrite.` prefixed properties on the commandline

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java, src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
As added in
- https://github.com/openrewrite/rewrite-maven-plugin/pull/726
=> Pull up State to ConfigurableRewriteMojo for use in additional Mojo

src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
=> Optionally resolve properties in yaml

suppressions.xml
Resolves: https://github.com/moderneinc/dependency-vulnerability-reports/issues/635
=> chore: update suppressions from 2024-02-28 vulnerability report

suppressions.xml
removing unnecessary suppressions
updating the until date for suppressions which still apply
=> Updating Suppressions

pom.xml, src/main/java/org/openrewrite/maven/ResourceParser.java
- Following https://github.com/openrewrite/rewrite/pull/4845
=> Add TomlParser

src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
As per https://maven.apache.org/ref/3.9.9/maven-core/apidocs/org/apache/maven/execution/MavenSession.html#getUserProperties()
Following
- https://github.com/openrewrite/rewrite/pull/5070
- https://github.com/openrewrite/rewrite/pull/5107
- https://github.com/openrewrite/rewrite/pull/5114
=> Add MavenSession.userProperties to MavenParser

pom.xml
=> OpenRewrite 8.55.2

.github/workflows/ci.yml
Update CI file to use new secret
=> Update regarding maven central

src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java, src/main/java/org/openrewrite/maven/ResourceParser.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UnwrapElseAfterReturn?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
=> Unwrap else block after return or throw statement

src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
More tightly/closely control setting of the charset to only effect the current parser's work and ensure that the charset is cleared when that work has completed.
Prior to this change, we were setting the charset on the first project when running on submodules was allowed and then allowing that to cascade into all of the subprojects. Secondarily to this, we were allowing the build charset -- which is only applicable to Java sources -- to impact Kotlin sources (UTF-8 required) and resources. 
N/A
@sambsnyd 
N/A
N/A
=> Prevent leaking of charset between projects and over into non-source set resources
