- src/main/java/org/openrewrite/maven/RewriteDiffMojo.java
There does not appear to be a `-f` flag for `git apply`:
https://git-scm.com/docs/git-apply
> instructions to run 'git apply' contain non-existing flag

- src/it/publish-skip-cyclone-dx-bom/invoker.properties
- src/it/publish-skip-cyclone-dx-bom/pom.xml
- src/it/publish-skip-cyclone-dx-bom/src/main/java/sample/HelloWorld.java
- src/it/publish-skip-cyclone-dx-bom/verify.groovy
- src/main/java/org/openrewrite/maven/RewritePublishMojo.java
This change allows the publish mojo to skip the building and attaching
of a CycloneDX BOM artifact to the project if the parameter
`skipCycloneDxBom` is set to true (default value is false).
Related to [#59][0], generating this artifact fails for projects where
the parent pom is not in Maven Central, so adding this property is
mostly a workaround to the failure but might have other uses as well.
[0]: https://github.com/openrewrite/rewrite-maven-plugin/issues/59
> publish: add 'skipCycloneDxBom' parameter

- .github/workflows/release.yml
- pom.xml
part of https://github.com/openrewrite/rewrite-maven-plugin/issues/79
This demonstrates how the current workflow of releasing could be uplifted to github actions; the biggest benefit being not requiring a shared set of credentials directly on the releaser's computers -- instead, stored as repository secrets.
Currently can be ran manually ran from the `actions` UI (though would be beneficial to one day have this trigger automatically on a `git tag` and push rather than the other way around).
An example of this in action can be seen here: https://github.com/slugstack/rewrite-definitions/runs/1751552089?check_suite_focus=true
Requires the following github secrets defined on the repository:
MAVEN_GPG_PASSPHRASE
MAVEN_GPG_PRIVATE_KEY
OSSRH_TOKEN
OSSRH_USERNAME
> github actions for automated release workflow

- pom.xml
- src/it/multi-module-project/pom.xml
- src/it/single-project/pom.xml
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
This enhancement enables rewrite's pom caching mechanism. The use of caching improves the execution time substantially after the cache has been primed. The poms are stored in a directory on the file system (the default is `~/.rewrite-cache/poms`). The cache is "on" by default and can be toggled via the 'pomCacheEnabled' configuration property.
> Adding pom caching to maven plugin

- src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/a/pom.xml
- src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/b/pom.xml
- src/test/resources-its/org/openrewrite/maven/PomCacheIT/multi_module_project/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteCycloneDxIT/multi_module_project/a/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteCycloneDxIT/multi_module_project/b/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteCycloneDxIT/multi_module_project/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/a/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/b/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/a/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/b/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/pom.xml
Remove the build plugin declaration from submodules, only have the plugin applied to the root pom.xml.
> remove build plugin from submodule pom xmls in tests

- src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
- src/test/java/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteCycloneDxIT/multi_module_with_cross_module_dependencies/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run/a/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run/a/src/main/java/sample/SampleA.java
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run/b/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run/b/src/main/java/sample/SampleB.java
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run_modules_with_different_recipe_sets/a/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run_modules_with_different_recipe_sets/a/src/main/java/sample/SampleA.java
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run_modules_with_different_recipe_sets/b/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run_modules_with_different_recipe_sets/b/src/main/java/sample/SampleB.java
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/multi_module_dry_run_modules_with_different_recipe_sets/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/single_project_discover/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/single_project_discover_multiple_dependencies/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/single_project_run/pom.xml
- src/test/resources-its/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT/single_project_run/src/main/java/sample/Sample.java
Tests with more "third-party dependencies" focus. Separate folder because these have more touchpoints.
> integration tests which consume third-party dependencies for the recipes received

- .github/workflows/ci.yml
- src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
- src/test/java/org/openrewrite/maven/RewriteRunIT.java
- src/test/java/org/openrewrite/maven/UsingRecipesFromExternalDependenciesIT.java
Add test coverage using windows-latest but file path separator output is different on windows.
This isn't perfect at the moment since these tests are doing a string output comparison using `contains("words and some/path/match")`, so I'll add a Disable annotation on some of these tests. But I do want to at least allow folks on windows machines to run the test suite locally.
> Feather in test coverage against windows machines

- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
- src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_default_output/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_verbose_output/pom.xml
closes https://github.com/openrewrite/rewrite-maven-plugin/issues/134
Now by default, `rewrite:discover` will only show top-level discoverable recipes rather than fully displaying `Descriptors:` underneath.
This output will receive more love in later PRs, but for this exact moment let's at least set the default to prevent this from blowing out the console log.
> rewrite:discover default should only show top-level discovered recipes

- README.md
- pom.xml
- src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java
- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
- src/main/java/org/openrewrite/maven/RewriteDryRunMojo.java
- src/main/java/org/openrewrite/maven/RewriteRunMojo.java
closes https://github.com/openrewrite/rewrite-maven-plugin/issues/141
Updated the javadoc on these classes to use the goals descriptions referenced from https://docs.openrewrite.org/reference/rewrite-maven-plugin
Result as it stands, could be quickly tidied up and possibly whether reference URL could be included:
```txt
Eliminate technical debt. At build time.
This plugin has 5 goals:
rewrite:cyclonedx
Produce a Cyclone DX BOM for publication to Maven repositories
rewrite:discover
rewrite:dryRun
rewrite:help
Display help information on rewrite-maven-plugin.
Call mvn rewrite:help -Ddetail=true -Dgoal=<goal-name> to display parameter
details.
rewrite:run
```
after
```
[INFO] rewrite-maven-plugin 4.1.1-SNAPSHOT
Eliminate technical debt. At build time.
This plugin has 5 goals: …
```
> Maven-plugin-plugin to generate rewrite:help

- pom.xml
- src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java
- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
- src/main/java/org/openrewrite/maven/RewriteDryRunMojo.java
- src/main/java/org/openrewrite/maven/RewriteRunMojo.java
- src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_reads_rewrite_yml/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_recipe_lookup_case_insensitive/pom.xml
cherry-picking polish from https://github.com/openrewrite/rewrite-maven-plugin/pull/150 to merge it in faster and it not be contingent on features
- Move `discovery` features to parameters to make them discoverable through `./mvnw rewrite:help` (closes #137)
- Make `rewrite.discover.filter` just `recipe` so it's easier to use (it's unlikely this was being aggressively used so we'll consider it not a big deal to have changed the parameter); make this case-insensitive, too.
- fix test which had `activeRecipe` instead of `activeRecipes`
- cleanup javadoc headers to be more succicint and use more present-tense verbage inkeeping with `help`
- rewrite-plugin bootstrap with activeRecipe from testing-frameworks
> fix rewrite.discover parameter discovery and polish help docs

- pom.xml
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
Pulled this snip out of of https://github.com/openrewrite/rewrite-maven-plugin/pull/150 this enables a way to do log printing with hierarchical levels with leftmost indent printing. This'll have value for a few other changes when printing out `usage`, `tree`, debug info, etc.
> simple indent method for formatting log messages

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
Building off of https://github.com/openrewrite/rewrite-maven-plugin/pull/156
- Move `activeRecipes` and `activeStyles` at the top of the `environment()` block.
- Tidy spacing.
- Could move some of the "Now running..." log messages into `debug` logging in the future
> polish execution status logging

- src/main/java/org/openrewrite/maven/RewriteDryRunMojo.java
- src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/fail_on_dry_run/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/fail_on_dry_run/src/main/java/sample/BadSpacing.java
closes openrewrite/rewrite-maven-plugin#139
Maven equivalent to https://github.com/openrewrite/rewrite-gradle-plugin/pull/52
```xml
...
<configuration>
<failOnDryRunResults>true</failOnDryRunResults>
</configuration>
...
```
> Configurable failOnDryRunResults

- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
- src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
change looks like:
was previously:
based off feedback and on reference pages:
https://docs.openrewrite.org/reference/recipes/maven/managedependencies
> Change discover display based on feedback and current reference documentation layout

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
Resource File Filter was ignoring properties and xml files. Added those file type so that recipe can run on those files.
> Fix Resource File Filter

- pom.xml
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
The RockdbMavenPomCache was updated to create a cache directory that is relative to the default or user provided input. Ref: https://github.com/openrewrite/rewrite/issues/491.
> Updated instantiation of RocksdbMavenPomCache.

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
Remove `scanClassPath` from the AbstractRewriteMojo per
https://github.com/openrewrite/rewrite/commit/072eed5505af7a3d9175d3f63e85393c4da893dd
> Remove `scanClassPath` from the AbstractRewriteMojo EnvironmentBuilder.

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
addendum to https://github.com/openrewrite/rewrite-maven-plugin/issues/185 and https://github.com/openrewrite/rewrite-maven-plugin/issues/186
> traverse recipes to leaf nodes first before checking type in order to handle composite recipes

- pom.xml
In lieu of having release versions dynamically deduced from `git tag`s, when performing a release, set the default policy be to bump the `minor` version when going to the next development version.
Note, if wanting to release a patch version, you can manually set the version to being `desiredVersion-SNAPSHOT`, e.g. `4.6.5-SNAPSHOT` would release `4.6.5`, but the key point here is that by default, the _next development version_ would bump the minor version. So, for example, releasing on `4.6.5-SNAPSHOT` would release `4.6.5`, then bump the development version to `4.7.0-SNAPSHOT`. Currently, using the default strategy, it would bump the version to `4.6.6-SNAPSHOT`. It's more likely we're wanting to bump the next version to the next-highest minor version than patch.
> Set default release policy to bump next development version using minor version

- pom.xml
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
this way:
- it shows up in helpdoc, 
- it's easier to be aware of the configuration parameter at all
- when it's declared as a Paramter, it can be configured within the pom.xml itself as a configuration field, e.g. `<skipMavenParsing>` in `<configuration>` under rewrite-maven-plugin
Kept the reference as `skipMavenParsing` in order to be backwards compatible with `-DskipMavenParsing`, vs. having this be referenced on the CLI as `-Drewrite.skipMavenParsing`
Inspired by https://github.com/openrewrite/rewrite-maven-plugin/issues/238
> Have skipMavenParsing be a declared parameter

- pom.xml
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Refactored MavenMojoProjectParser to be compatible with the changes made to rewrite-7.17.0. Specifically, the `SourceSet` provenance information is now managed by the JavaParser. The project parser now uses the SourceSet markers from the JavaParser.
> Rework MavenMojoProjectParser to use SourceSet from parser

- pom.xml
- src/main/java/org/openrewrite/maven/InitMojo.java
- src/test/java/org/openrewrite/maven/ConfigureMojoIT.java
- src/test/java/org/openrewrite/maven/InitMojoIT.java
- src/test/resources-its/org/openrewrite/maven/ConfigureMojoIT/single_project/pom.xml
- src/test/resources-its/org/openrewrite/maven/InitMojoIT/single_project/pom.xml
Was playing around with these locally, and noticed they each take a differently formatted `dependencies` argument, which isn't immediately clear from the outset. It's due to on the one hand `AddPlugin` in `init`, versus `ChangePluginDependencies` in `configure`. Having tests that verify and highlight these differences should help discoverability.
I'd even be inclined to change most likely the `init` mojo to use the gav form of dependencies used in `configure`. I guess that could be achieved by also using `.doNext(new ChangePluginDependencies(groupId, artifactId, dependencies))` in `init` instead of adding the dependencies through `AddPlugin`. What would you say to such a suggested change?
Also added a log statement as inexplicably (for me) the InitMojoIT silently ignored the mojo run, …
> Add integration tests for init and configure mojos

- README.md
- pom.xml
- src/test/java/org/openrewrite/maven/BasicIT.java
- src/test/java/org/openrewrite/maven/ConfigureMojoIT.java
- src/test/java/org/openrewrite/maven/InitMojoIT.java
- src/test/java/org/openrewrite/maven/RemoveMojoIT.java
- src/test/java/org/openrewrite/maven/RewriteCycloneDxIT.java
- src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
- src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
- src/test/java/org/openrewrite/maven/RewriteRunIT.java
Group assertj dependencies together
Remove parallel execution
Move resources and test resources to the top of the build section for cleaner visibility
Process help simplification
Prevent filtering of erroneous files by itf-maven-plugin
README example with dependencies
Inline single-use version numbers for consistency
Test resource filtering false
Remove unused surefire and invoker plugins
Rm gitkeep
Leverage anySatisfy
> Refactoring polish

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- src/test/java/org/openrewrite/maven/InitMojoIT.java
- src/test/java/org/openrewrite/maven/RemoveMojoIT.java
- src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
- src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
- src/test/java/org/openrewrite/maven/RewriteRunIT.java
Test polish, leverage anySatisfy for matching single line partial contains
Add fail-at-end flags to provide better info per test-run in the event of failure
> Add fail-at-end flags to provide better info per test-run in the event of failure

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Taking inspiration from https://github.com/apache/maven-plugins/blob/a007e769ed5825774d5c31ec06c0013c8ee2b4d4/maven-scm-publish-plugin/src/main/java/org/apache/maven/plugins/scmpublish/AbstractScmPublishMojo.java#L317-L336
https://github.com/openrewrite/rewrite-maven-plugin/issues/268
Something to be aware of: is there a possible `null` on getServers() if decryption fails?
> Settings decryption request

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/test/java/org/openrewrite/maven/BasicIT.java
- src/test/resources-its/org/openrewrite/maven/BasicIT/null_check_profile_activation/pom.xml
- src/test/resources-its/org/openrewrite/maven/BasicIT/null_check_profile_activation/settings.xml
Fixes https://github.com/openrewrite/rewrite-maven-plugin/issues/269
> Handle profile activation property being null

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
`maven.getSourcePath()` returns a Path of `pom.xml`.
Then `ResourceParser` includes the baseDir in the path of the files it looks for (`/user/.../pom.xml`).
So, `alreadyParsed` does not detect the file has been parsed and adds another `XML` without the maven marker.
> include the baseDir on the path of the maven pom if the sourcePath is `pom.xml`

- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
Let recipes and styles configured via rewrite namespace override active recipes and styles. Fixes: #314
> Let recipes and styles configured via rewrite namespace override active recipes and styles.

- src/main/java/org/openrewrite/maven/ConfigureMojo.java
- src/main/java/org/openrewrite/maven/InitMojo.java
- src/main/java/org/openrewrite/maven/RemoveMojo.java
- src/test/java/org/openrewrite/maven/ConfigureMojoIT.java
Even though I wrote the integration tests, I still had to look up how to execute the commands again. :upside_down_face: 
Adding examples to `./mvnw org.openrewrite.maven:rewrite-maven-plugin:help` ought to help discover their usage.
> Document Init, Configure and Remove Mojos for discovery through :help

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Previously, it was assumed that an aggregate project was also each module's parent. This is actually not the case and a maven project can include an aggregate project (one that has sub-modules) where the sub-modules have a different parent.
The resolution logic was not correctly including pom files that were either a sibling or were included as part of an aggregate pom.
See this project for an example of an aggregate that is not a module's parent: 
https://github.com/tkvangorder/disconnected-parents/
> Include any transitive/aggregate poms when parsing a project

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/main/java/org/openrewrite/maven/ResourceParser.java
Changes:
- ResourceParse file traversal is scoped to the current maven project.
fixes #352.
> Scope ResourceParse to the current maven project.

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Changes:
- parseMaven will return a `Maven` `Xml.Document` that matches the current project.
fixes #351
> Collect maven poms with LinkedHashSet.

- src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
- src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/main/java/org/openrewrite/maven/ResourceParser.java
Reworked the maven plugin to run on the last project in the maven session. The plugin will then iterate through all of the projects in the maven session (in reactor order) to parse source files and will then run the recipe across all source files (in all projects).
> Refactoring to the plugin to only parse and run on the last project. fixes #349

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Changes:
- Styles in maven projects will be auto-detected when a style is not provided.
fixes #378
> Auto-detect style if the list of styles is empty in MavenMojoProjectParser.

- pom.xml
- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/test/java/org/openrewrite/maven/ConfigureMojoITNoActiveRecipe.java
- src/test/resources-its/org/openrewrite/maven/ConfigureMojoITNoActiveRecipe/single_project/pom.xml
Fixing a null value in the activeRecipes collection causing the discover goal to fail even if no recipes should be run. This can happen when having a property as the value of the recipe name and that property is null. Then the collection will only contain a single element which is null
> Upping maven-filter from 3.2.0 (Aug 2020) to 3.3.0 (Jun, 2022)

- README.md
Documentation for the `bootstrap` profile within the [README.md](https://github.com/openrewrite/rewrite-maven-plugin/compare/main...dsibilio:fix/grammar-check?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) file looks broken as-is.
This PR just tries to simplify the docs and make the relevant sentence more understandable.
> Improve documentation for the 'bootstrap' profile

- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
- src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_multi_module/a/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_multi_module/b/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDiscoverIT/rewrite_discover_multi_module/pom.xml
Allows for the execution of the `discover` goal from non-Maven projects.
Will only execute the `discover` goal once per project reactor rather than once for each module.
Fixes https://github.com/openrewrite/rewrite-maven-plugin/issues/386.
> Improve 'discover' goal behaviour for multi-module/no projects

- .github/dependabot.yml
- pom.xml
Changes:
- Plugin is compatible with Java 8.
- Added the `checkstyle` dependency as ignored in `dependabot.yaml`.
fixes #393
> Pinned com.puppycrawl.tools:checkstyle back to 9.3

- pom.xml
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/main/java/org/openrewrite/maven/ResourceParser.java
Add the ability to configure which files will be parsed as plain text. If no configuration is applied the defaults for the plugin are: 
```
**/META-INF/services/**
**/.gitignore
**/.gitattributes
**/.java-version
**/.sdkmanrc
**/*.sh
**/*.bash
**/*.bat
**/*.ksh
**/*.txt
**/*.jsp
```
This is related to https://github.com/openrewrite/rewrite/issues/2134
> Configure a set of file masks to be included in plain text parsing.

- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
this wasn't actually matching a Dockerfile in the project root dir; now it does
> Fixed Dockerfile in default plainTextMasks

- pom.xml
Address CVEs by importing jackson and netty boms and pining those boms to versions that address CVEs.
https://github.com/moderneinc/dependency-vulnerability-reports/issues/467
> Fix Jackson/Netty CVE issues

- pom.xml
- remove junit-jupiter.version property because we have only a single location.
> fix - BOM Usage instead of separate dependencies with properties. (#504)

- src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
Just a simple way to skip plugin execution by property to allow more granular control in the lifecycle without profiles.
> feat: Add rewrite.skip to skip execution

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
LinkedHashMap instead of HashMap, to mimic https://github.com/openrewrite/rewrite/commit/8d7eff280c016aa7c47238898062c29457f81ce4
https://github.com/openrewrite/rewrite/issues/1753
https://github.com/openrewrite/rewrite/issues/3219
> Use a defined order for projectMap

- .github/workflows/publish.yml
This ensures we use the latest versions of rewrite modules with each release, in lieu of using `RELEASE` which made it into the released pom.xml.
> Bump rewrite.version properties on release

- pom.xml
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Created this PR because unsure about `J.clearCaches();` which has been removed in rewrite8.
> Bump rewrite version to 8.0.0

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/main/java/org/openrewrite/maven/ResourceParser.java
While the recipe running will still load all parsed source files into memory (by collecting the stream into a List), the parser API can be clients which require streaming support.
> Implement streaming for source file parsing

- src/main/java/org/openrewrite/maven/ResourceParser.java
The error message for resources with parse errors.
The error message currently says "There were problems parsing 7 + sources:".
Looking at the git history the plus sign in the output is probably from a string concatenation that made it into the string literal by accident.
n.a.
> Remove unwanted characters from error message

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/main/java/org/openrewrite/maven/ResourceParser.java
The JVM-based parsers should not all share the same `JavaTypeCache`, especially not in multi-module builds or across source set boundaries.
> Remove global shared `JavaTypeCache`

- pom.xml
jackson-bom.version 2.15.0 -> 2.15.2
Vulnerability report.
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.1
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.2
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.3 (withheld, as BOM missing)
> Jackson 2.15.2

- pom.xml
Netty to 4.1.94
Rsocket to 1.1.4
Vulnerability report.
[Netty 4.1.94.Final released](https://netty.io/news/2023/06/19/4-1-94-Final.html) on 19-Jun-23
[Netty 4.1.93.Final released](https://netty.io/news/2023/05/25/4-1-93-Final.html) on 25-May-23
[Netty 4.1.92.Final released](https://netty.io/news/2023/04/25/4-1-92-Final.html) on 25-Apr-23
[Netty 4.1.91.Final released](https://netty.io/news/2023/04/03/4-1-91-Final.html) on 03-Apr-23
[Netty 4.1.90.Final released](https://netty.io/news/2023/03/14/4-1-90-Final.html) on 14-Mar-23
https://github.com/rsocket/rsocket-java/releases/tag/1.1.4
> Bump Netty to 4.1.94 & Rsocket to 1.1.4

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/test/java/org/openrewrite/maven/MavenMojoProjectParserTest.java
MavenMojoProjectParser uses `java.specification.version` as default for source and target version.
"Fix": https://github.com/openrewrite/rewrite-maven-plugin/issues/593
>  Use java.specification.version when no source and target version exists

- pom.xml
- src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
- src/test/java/org/openrewrite/maven/RewriteRunIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/rewrite.yml
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/rewrite.yml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/rewrite.yml
Not much code here - but hours of investigation >_<
* https://stackoverflow.com/questions/76757630/maven-plugin-plugin-descriptor-goal-does-not-generate-mojo-description-documenta 
* https://stackoverflow.com/questions/76765750/plugin-info-html-file-not-being-generated-when-running-maven-site
We can then run `mvn process-classes` and then `mvn site` to get auto-generated documentation of our plugins.
> Update the pom.xml so auto-generation works for docs

- README.md
- pom.xml
Consistency with other OpenRewrite projects; seeing string concatenation in #601 
Any risk of this breaking our compatibility with Java 8 for src/main?
> Allow the use of Java 17 in tests

- .github/workflows/pages.yml
- pom.xml
Deploy plugin docs to GitHub Pages at 
https://openrewrite.github.io/rewrite-maven-plugin/plugin-info.html
We want to link to the generated docs, such that they are always up to date.
Would we want to swap for a different style?
Would we want to limit produced pages through a site.xml?
Intended to mostly replace: https://docs.openrewrite.org/reference/rewrite-maven-plugin
https://github.com/openrewrite/rewrite-docs/blob/master/reference/rewrite-maven-plugin.md
> Deploy plugin docs to GitHub Pages

- suppressions.xml
Removed outdated suppression elements.
The Guava suppression should no longer be necessary after https://github.com/openrewrite/rewrite-python/pull/63
Keep the file maintainable.
Also logged as a recipe request: https://github.com/openrewrite/rewrite-java-dependencies/issues/24
> Remove outdated suppressions

- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
Indentation of discover mojo is now as expected.
Part of #630.
> Fix indentation of available recipes output (#630)

- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
* sort just for output, not in any of the APIs returning the data
* sort case insensitive, which is generally better suited for humans reading a list
Sort the lists produced by the discover mojo output for easier reading by humans.
Fixes #630
Looks like this now:
> Sort output of discover mojo (#630)

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Eclipse Tycho produces artificial Maven POMs during the build, which should be ignored by the POM scanner.
Fixes #634.
Ignore temporary POMs generated by Eclipse Tycho during the scan for POMs.
The debug log now shows the real POMs being picked up during the scan (compare to issue):
```
[DEBUG] Project [eclipse-cs Maven Parent] Base directory : 'C:\dev\eclipse-cs\git\eclipse-cs'
[DEBUG] Project [eclipse-cs Maven Parent]   Collected Maven POM : 'C:\dev\eclipse-cs\git\eclipse-cs\pom.xml'
[DEBUG] Project [eclipse-cs Maven Parent]   Collected Maven POM : 'C:\dev\eclipse-cs\git\eclipse-cs\net.sf.eclipsecs.branding\pom.xml'
[DEBUG] Project [eclipse-cs Maven Parent]   Collected Maven POM : 'C:\dev\eclipse-cs\git\eclipse-cs\net.sf.eclipsecs.checkstyle\pom.xml'
[DEBUG] Project [eclipse-cs Maven …
```
> Ignore Tycho generated POMs

- src/test/java/org/openrewrite/maven/RewriteCycloneDxIT.java
Fixes #636.
Just ignores a warning during test, which may appear on some systems, but not on all.
> Ignore Maven POM cache warning in test

- pom.xml
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/main/java/org/openrewrite/maven/ResourceParser.java
Add kotlin parser to support Maven projects.
Verified in https://github.com/vert-x3/vertx-client-services and running recipe `org.openrewrite.kotlin.format.AutoFormat` and `org.openrewrite.java.ChangeType`, it works well.
> Add kotlin parser

- README.md
The link to the OpenRewrite Quickstart Guide was broken.
I want people to find the correct website in the README.
> fixed link to quickstart guide

- pom.xml
- src/main/java/org/openrewrite/maven/ResourceParser.java
Adds GroovyParser to the ResourceParser so we get source files with content for Groovy sources and Jenkinsfiles, instead of Quarks.
Fixes https://github.com/openrewrite/rewrite-maven-plugin/issues/662
> Adds GroovyParser (#662)

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
With empty lists of main or test, Java or Kotlin files avoid invoking the parsers completely. That's more performant and avoids any bad side effects during initialization of the parsers.
Fixes #658.
You may want to reformat, I used the Eclipse formatter.
> Avoid calling parsers when there are no source files

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- Simplify logic surrounding building Java & Kotlin parsers when there are no source files to parse.
- Also simplify logic related to log statements, markers & return value.
- https://github.com/openrewrite/rewrite-maven-plugin/pull/660
Readability suffered a bit when mentally trying to parse what we had before.
```java
Stream<? extends SourceFile> cus = mainJavaSources.isEmpty() ? Stream.empty()
: Stream.of(javaParserBuilder).map(JavaParser.Builder::build)
.flatMap(parser -> parser.parse(mainJavaSources, baseDir, ctx));
```
Then further improvements from there on as spotted.
Could have merely gone for `javaParserBuilder.build()` in ternary, but that didn't yet help readability much.
> Simplify logic surrounding building of Java & Kotlin parsers.

- src/main/java/org/openrewrite/maven/ResourceParser.java
Fixes #671.
As suggested in the discussion, change the message to indicate that quark files are not parsed.
Also change the unit from "Mb" to "MB", since "Mb" indicates Megabit. Add a blank between numbers and unit for readability and to be consistent with output in other parts of the code.
Only the log message which is emitted for large non parseable files.
Clarifies the confusion described in #671.
> Improve quark parsing message

- .github/workflows/ci.yml
- pom.xml
Java 21+ warns about active annotation processors, unless the compiler has been explicitly configured to accept them.
See https://bugs.openjdk.org/browse/JDK-8310061
Remove this warning from the build process, when running Maven on Java 21+:
Doesn't have any side effects on older JDKs.
Further references: https://inside.java/2023/07/29/quality-heads-up/ or https://github.com/khmarbaise/jdk21
> Avoid annotation processor warning

- .sdkmanrc
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Parse Maven wrapper files even if `parseAdditionalResources = false`.
Ensures consistent markers on Maven wrapper files, to allow `UpdateMavenWrapper` to access the active Maven version.
> Always parse Maven wrapper files

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/main/java/org/openrewrite/maven/ResourceParser.java
Pass the existing `ExecutionContext` into `ResourceParser`, instead of creating a new `InMemoryExecutionContext`.
Reuse any `ParsingEventListeners` or `Consumer<Throwable>` registered on the original ExecutionContext.
Fixes #622
- #622
> Reuse ExecutionContext for ResourceParser

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Fix bug where Kotlin test source parsing actually parsed main dir a second time, and test sources were later parsed as additional resources
> Kotlin source dir parsing bugfix

- src/main/java/org/openrewrite/maven/MeterRegistryProvider.java
Different instances of `MeterRegistry` are created using `MeterRegistryProvider#registry()`.
Use the maven plugin with `rewrite.metricsUrl=LOG`
> Fix metric registry creation

- .github/workflows/bump-snapshots.yml
- .github/workflows/ci.yml
- .github/workflows/pages.yml
- .github/workflows/publish.yml
- .sdkmanrc
- pom.xml
Revert back to Java 17 instead of Java 21.
Fixes https://github.com/openrewrite/rewrite/issues/3826
We saw users report failures running on Java 8 due to `MalformedParametersException: Invalid parameter name ""` after switching from https://github.com/openrewrite/rewrite-maven-plugin/compare/v5.14.1...v5.15.0
- https://github.com/openrewrite/rewrite/issues/3826
> Revert to Java 17 after openrewrite/rewrite#3826

- src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
- src/test/java/org/openrewrite/maven/RewriteRunParallelIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunParallelIT/multi_module_project/a/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunParallelIT/multi_module_project/a/src/main/java/sample/MyInterface.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunParallelIT/multi_module_project/a/src/main/java/sample/SimplifyBooleanSample.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunParallelIT/multi_module_project/b/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunParallelIT/multi_module_project/b/src/main/java/sample/EmptyBlockSample.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunParallelIT/multi_module_project/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunParallelIT/multi_module_project/rewrite.yml
Since PR #720 merged, I made more tests on different projects, and there is some cases where recipes are still executed before the end of all module packaging when building with Maven parallel build .
I analyzed the implementation of the `installAtEnd` and `deployAtEnd` options of the `maven-install-plugin`:  
https://github.com/apache/maven-install-plugin/blob/master/src/main/java/org/apache/maven/plugins/install/InstallMojo.java  
and `maven-install-plugin` plugins:
https://github.com/apache/maven-deploy-plugin/blob/master/src/main/java/org/apache/maven/plugins/deploy/DeployMojo.java
It uses mojo Context to store "state markers", presence of marker means project was "processed".   
This MR is based on this implementation.   
Fix #719
@timtebeek 
I have added a `RewriteRunParallelIT` …
> Delaying execution to the end of multi-module project with Maven parallel build

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/test/java/org/openrewrite/maven/MavenMojoProjectParserTest.java
Create separate JavaVersion markers for src/main and src/test, based on their relative properties.
Fall back to src/main for src/test when not explicitly set.
Allows adopting Java 17 language features in tests when src/main still uses Java 8, as evaluated by HasJavaVersion & UsesJavaVersion.
Files like the Maven wrapper files and other additional resources outside of src/main and src/test now get the runtime Java version marker, as they do not explicitly declare their Java version.
We could continue to assign the wrong src/main JavaVersion to src/test files for projects that use a different version for tests. That might end up surprising folks though, and does not allow some recipes to make changes in src/test when src/main uses a lower version.
Prompted by a question for a community …
> Separate JavaVersion markers for src/main and src/test

- src/main/java/org/openrewrite/maven/MavenLoggingResolutionEventListener.java
- src/main/java/org/openrewrite/maven/MavenLoggingResolutionListener.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Added a logging `ResolutionListener` on `MavenMojoProjectParser`.
Identify maven resolution issues (#703).
No
No
Current maven debug output is not helpful regarding the plugin dependency resolution errors.
No
> Adding a logging resolution event listener

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
This way we can target `.mvn/maven.config` files knowing what version of Maven (wrapper) was used to parse the project.
> Add Maven BuildTool marker to .mvn/maven.config

- pom.xml
The build complains about incomplete Java level settings. Once in the main source compilation ([example from main branch build](https://github.com/openrewrite/rewrite-maven-plugin/actions/runs/8083030796/job/22085154131#step:4:30)), and again in the test source compilation (only if using a JDK > 17). The PR avoids both warnings.
```
[INFO] --- compiler:3.12.1:compile (default-compile) @ rewrite-maven-plugin ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 23 source files with javac [debug target 1.8] to target\classes
[WARNING] bootstrap class path not set in conjunction with -source 8                                      <---------------------
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is …
```
> Avoid 2 Java level warnings of the compiler plugin

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
https://rewriteoss.slack.com/archives/C01A843MWG5/p1709621242673569
Folks might run in unexpected ways, from different directories or in multi module projects, and similarly place rewrite.yml in unexpected paths. Adding a log line gives us the option to explore what's been evaluated. Additionally moved a method that was exclusively used by `RewriteDiscoverMojo` to that mojo from `AbstractRewriteMojo`.
> Move `getRecipeDescriptor` and add debug log on rewrite.yml path

- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/test/java/org/openrewrite/maven/RewriteRunIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/checkstyle_inline_rules/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/checkstyle_inline_rules/src/main/java/sample/SimplifyBooleanSample.java
Inline checkstyle config from `maven-checkstyle-plugin` can now be parsed, in addition to reading file references from the `configLocation` tag.
Support more of the various config options that exist for `maven-checkstyle-plugin`, to capture more style instructions that exist in existing codebases. 
I didn't think of an obvious positive test case, but I'm happy to take suggestions. For now, just look for the absence of parsing errors.
> Parse inline checkstyle config from maven-checkstyle-plugin

- src/main/java/org/openrewrite/maven/AbstractRewriteBaseRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
Adds rewrite.exportDatatables property to Maven Plugin to allow Datatable information to be exported as a CSV. 
See the[ Rewrite-Core PR](https://github.com/openrewrite/rewrite/pull/4087) for more information. 
Note that the datatable output path is currently set to target/rewrite/datatables
These changes are dependent on the changes in [this rewrite-core pr](https://github.com/openrewrite/rewrite/pull/4087)
> Printable Recipe Datatables

- src/main/java/org/openrewrite/maven/AbstractRewriteBaseRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
Fixes #781
After log changes for each result, sum estimate time saved and log it.
OpenRewrite is working fine and it is very helpful. To show the importance and the time saved, I think it's interesting to show the estimate time saved.
The same was gone for [Gradle plugin ](https://github.com/openrewrite/rewrite-gradle-plugin/pull/294)
> Estimate time saved

- pom.xml
* Use Maven enforcer to clearly indicate the need for Java 17 during build, as the usage of Java 8 on the classpath may lead to confusion.
* Also enforce the same minimum Maven version as used in the Maven wrapper to ensure both mvn and mvnw create similar output.
If one tries to build on a JDK less than 17, the error messages are rather confusing (because the maven compiler plugin complains about some unknown symbols only). Make the error more obvious by using Maven enforcer instead.
> Use Maven enforcer for Java and Maven minimum versions

- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
These were added in https://github.com/openrewrite/rewrite-maven-plugin/pull/724 in January, four months ago.
Should have been time enough to clear out their usage, and update the reference documentation:
https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html
Would this warrant a major version change? We're at 5.32.1 right now.
Anything else we'd like to include if we are to bump the version number?
> Drop deprecated non prefixed properties

- src/main/java/org/openrewrite/maven/MavenLoggingResolutionEventListener.java
Hide stack trace by default, but log it at debug level such that it is accessible when troubleshooting through `-X`.
Folks were alarmed by the full stack trace, incorrectly concluding that recipes aren't running. As per
- https://github.com/openrewrite/rewrite/issues/4101
Will still see if we can not contact failing repositories unnecessarily to really fix openrewrite/rewrite#4101
> Log stacktrace for repositoryAccessFailed at debug level, not warn

- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/test/java/org/openrewrite/maven/RewriteRunIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/plaintext_masks/.in-root
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/plaintext_masks/from-default-list.py
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/plaintext_masks/in-root.ignored
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/plaintext_masks/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/plaintext_masks/rewrite.yml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/plaintext_masks/src/main/java/sample/Dummy.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/plaintext_masks/src/main/java/sample/in-src.ext
Add `rewrite.additionalPlainTextMasks` plugin option
The default list is super long and it was impossible to extend it - only override, which meant users would need to copy paste it + add their additional masks
> feat: option to add `additionalPlainTextMasks`

- src/main/java/org/openrewrite/maven/ResourceParser.java
Added accepted directories to accept all recursive directories within "src".
Previously it only checked whether the path contains one of the DEFAULT_IGNORED_DIRECTORIES. 
Now it checks whether the path also contains one of the DEFAULT_ACCEPTED_DIRECTORIES.
Now "src" will return false almost instantly and will not return true although there could be a build or out folder within the "src" folder.
Motivation was the open Issue #850. This is a fix to this issue and maybe a feature to be considered.
- Fixes https://github.com/openrewrite/rewrite-maven-plugin/issues/850
> Accept any directories under `src` in `ResourceParser`

- .gitignore
- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- src/test/java/org/openrewrite/maven/BasicIT.java
- src/test/resources-its/org/openrewrite/maven/BasicIT/snapshot_ok/pom.xml
Fix download warnings for SNAPSHOT components
- Fix https://github.com/openrewrite/rewrite/issues/4508
No
@timtebeek 
No
No.
> Fix download snapshot warnings

- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
The rewrite.resolvePropertiesInYaml flag introduced in #741 was only applied to the yaml file from the configLocation.
This PR also applies the flag to recipes loaded from the classpath.
> Honor `rewrite.resolvePropertiesInYaml` flag in classpath scanning

- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
I have added a configuration to ensure that Jelly files (with `.jelly` extension) are properly recognized as text files. Currently, `*.jelly` files are treated as quarks (unidentified files).
This change was prompted by the recent release of [the AddJellyXmlDeclaration recipe](https://docs.openrewrite.org/recipes/jenkins/addjellyxmldeclaration). The recipe requires the `additionalPlainTextMasks` option to function correctly. Here's the complete Maven command:
```bash
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
-Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-jenkins:RELEASE \
-Drewrite.activeRecipes=org.openrewrite.jenkins.AddJellyXmlDeclaration \
-Drewrite.exportDatatables=true \
-Drewrite.additionalPlainTextMasks=**/*.jelly
```
As [discussed …
> fix: Jelly files should be considered text files.

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- Fix #650 
Exclude pom generated by org.apache.maven.plugins:maven-shade-plugin and com.outbrain.swinfra:ci-friendly-flatten-maven-plugin
> Ignore generated pom by maven-shade-plugin and ci-friendly-flatten-maven-plugin

- pom.xml
Appeared unused, or at least usage patterns not clear, and lead to having to coordinate version numbers across rewrite-kotlin and here, with [periodic reminders like this one](https://github.com/openrewrite/rewrite-maven-plugin/pull/904).
Any reason this was added before that I might have missed @sambsnyd ?
Looks to have been added in two parts:
- https://github.com/openrewrite/rewrite-maven-plugin/commit/b7c8126a7327324a9c41a6ef95d8745678790819
- https://github.com/openrewrite/rewrite-maven-plugin/commit/98ea8052bcb678b8c777dada0351450a0c12bb46
> Drop Jackson Kotlin module and dependency management for now

- pom.xml
The license should be included in POMs being published to Maven Central
> Apply MSAL license when generating POMs

- .github/workflows/ci.yml
- .gitignore
- .mvn/develocity.xml
- .mvn/extensions.xml
- .mvn/wrapper/maven-wrapper.properties
- pom.xml
- src/test/java/org/openrewrite/maven/BasicIT.java
- src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
Add configuration for develocity build cache.
Speed up the builds.
- https://docs.gradle.com/develocity/maven-build-cache/
- https://docs.gradle.com/develocity/maven-get-started/
> Enable Develocity remote build cache on CI

- src/main/java/org/openrewrite/maven/AbstractRewriteBaseRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
- src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
Makes it easier to troubleshoot recipe execution errors that do not result in source related exceptions.
- Fixes https://github.com/openrewrite/rewrite-maven-plugin/issues/940
Now we log a warning for the first caught throwable, but do not halt execution or report subsequent warnings.
@philippe-granet 
We could choose to log warnings beyond the first, or even halt execution. That's a more drastic change though, and perhaps good to first, for a while, raise the visibility of these caught throwables.
- https://github.com/openrewrite/rewrite-maven-plugin/issues/940#issuecomment-2635127698
> Report first `Throwable` caught in `InMemoryExecutionContext.onError`

- pom.xml
- src/main/java/org/openrewrite/maven/AbstractRewriteBaseRunMojo.java
- src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
- src/main/java/org/openrewrite/maven/MeterRegistryProvider.java
- suppressions.xml
- removed consumers of `PrometheusRSocketClient` and related dependencies
- removed plugin properties `rewrite.metricsUri`, `rewrite.metricsUsername` and `rewrite.mertricsPassword`
This dependency is no longer required and indirectly contains a vulnerability from https://mvnrepository.com/artifact/org.xerial.snappy/snappy-java
No
@knutwannheden 
No
Vulnerable dependency https://mvnrepository.com/artifact/org.xerial.snappy/snappy-java/1.1.10.1
> Remove obsoleted `PrometheusRSocketClient`-based `MeterRegistryProvider`

- pom.xml
- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
An extra `listSourceFiles` method to parse sources only for:
- src/main/java
- src/test/java
I am not very certain about the naming here. The:
```java
public enum MavenScope {
MAIN,
TEST
}
```
could maybe be improved. The intention is here to match it with the `main` and `test` sourceSets of Gradle. I am open to all suggestions!
> Add maven-scope to the MavenMojoProjectParser, so `listSourceFiles` can be used partially

- src/main/java/org/openrewrite/maven/AbstractRewriteBaseRunMojo.java
- src/test/java/org/openrewrite/maven/BasicIT.java
Fix the Gaguge issue that was causing this warning:
```
[WARNING] This Gauge has been already registered (MeterId{name='cache.size', tags=[tag(cache=Maven POMs - default)]}), the Gauge registration will be ignored. Note that subsequent logs will be logged at debug level.
```
@timtebeek
> Remove gauge warning

- src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
- Fixes #980
This mimics what we do for the rewrite-gradle-plugin:
https://github.com/openrewrite/rewrite-gradle-plugin/blob/c64b6b61061ef4d01f6fc3a7db723fb4d0c6f0ab/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L932
For this then to get picked up in `EncodingDetectingInputStream`
https://github.com/openrewrite/rewrite/blob/49e4463193185c50252e2282f45278fb56e09f56/rewrite-core/src/main/java/org/openrewrite/internal/EncodingDetectingInputStream.java#L27
> Also store Charset on `ParsingExecutionContextView`

- src/main/java/org/openrewrite/maven/RewriteTypeTableMojo.java
- src/test/java/org/openrewrite/maven/RewriteTypeTableIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/b/src/main/java/sample/EmptyBlockSample.java
- src/test/resources-its/org/openrewrite/maven/RewriteTypeTableIT/typetable_default/pom.xml
Add a new goal to the rewrite-maven-plugin to create type tables.
Parity for folks using Maven, as up to now that had only been [available for Gradle](https://github.com/openrewrite/rewrite-build-gradle-plugin/blob/17964990a5d33cc6c025c315bd87e5eb0e3fd0eb/src/main/java/org/openrewrite/gradle/RecipeDependenciesTypeTableTask.java#L32-L37).
Figured I'd reuse as much as possible, while working around the fact that Maven does not easily allow resolving two versions. By using a profile folks should be able to clearly document the steps to recreate a type table, without it interfering with recipe runs on the same recipe module.
@nmck257 I believe this was relevant for you all there right?
Briefly explored plugin `<dependency>`, but that would not allow for more than one version of an artifact, …
> Create type tables for argument GAVs in Maven

- src/test/java/org/openrewrite/maven/RewriteRunIT.java
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/command_line_options_json/pom.xml
- src/test/resources-its/org/openrewrite/maven/RewriteRunIT/command_line_options_json/src/main/java/sample/SomeClass.java
- Added a new example to show an example of passing a JSON string for a `rewrite.options` option.
> Adding example of passing JSON as a `rewrite.options` argument value
